### PR TITLE
Syncing with master

### PR DESCRIPTION
**Pull request by jgharston**

### CODE REVIEW

**Comment by soruk42** [comment]
Something serms to be amiss with your branch, this time it's only touching the makefiles, moving the spec into build/ and touching tests. No code changes have been inclided here.

**Comment by soruk42** [comment]
Right. I've done some manual merging, and have applied most of it. I backed out the palette change for 16-colours in SDL, as the brightness of colours 1-7 didn't look right, compared to RISC OS. (I can live with the dimmer 8-15 colours, as Brandy doesn't (yet?) support flashing palette colours.)

**Comment by jgharston** [comment]
Michael McConnell wrote:
> backed out the palette change for 16-colours in SDL, as the brightness
> of colours 1-7 didn't look right, compared to RISC OS. (I can live
> with the dimmer 8-15 colours, as Brandy doesn't (yet?) support
> flashing palette colours.)

On a platform with non-flashing colours, 0-7 are the dimmer colours,
8-15 are the brighter colours, see
http://mdfs.net/Info/Comp/BBC/Display/Colours/Physical.htm and
http://beebwiki.mdfs.net/Physical_colour_numbers

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by soruk42** [comment]
While I see where you're coming from on that, but as I'm trying to make the graphics as similar to RISC OS as I can, I don't want to break the appearance for colours 0-7. So, I've implemented SWI "Brandy_Swap16Palette", takes no parameters, and swaps the dim and the bright colours round. This is reset on MODE change.

**Comment by soruk42** [comment]
I've added to the top-level makefiles, the option to read from environment variable BRANDY_BUILD_FLAGS so you can add additional defines without having to modify the makefiles - this might be useful for your keyboard work instead of maintaining separate makefiles?

**Pull request merged**
