### PR TITLE
GSTrans and function keys

### PR DESCRIPTION
**Pull request by jgharston**
05-Jan-2019

kbd_fnkeyset(), kbd_fnkeyget() code all pulled together.
Added calls to kbd_readline().
GSTrans returns string length, allows |@ in *KEY strings.

Builds tested:
 DJGPP, MinGW, WinSDL

### CODE REVIEW

**Comment by soruk42** [comment]
I've merged these in. It might not show up as a merge as I had to do some bits manually.

**Comment by soruk42** [comment]
And - if I read it right, from your tag in target.h, it's your birthday today? Happy birthday! It was mine two days ago.

**Comment by jgharston** [comment]
On 07-01-2019 11:40, Michael McConnell wrote:
> And - if I read it right, from your tag in target.h, it's your
> birthday today? Happy birthday! It was mine two days ago.

There seems to be a load of programmer-types around this weekend.
Dave H on Saturday, a handful of other StarDotters last week and
this week. Must be something about being born in the middle of
winter :)

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by soruk42** [comment]
I've manually merged your latest code.

HOWEVER - it won't build correctly on Unix, as in function kbd_get() you're using a function getch() that doesn't exist as a function in the Brandy code, nor is it a library function in Unix.

**Comment by jgharston** [comment]
Michael McConnell wrote:
> HOWEVER - it won't build correctly on Unix, as in function kbd_get()
> you're using a function getch() that doesn't exist as a function in
> the Brandy code, nor is it a library function in Unix.

Ah, I thought I'd carefully #ifdef'd around everything so only the MinGW 
and
DJGPP builds use the new code, as I hadn't started looking at the code 
the
other builds were using. I'll have a look later.

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by soruk42** [comment]
Ah, if you mean NEWKBD only works on those platforms, then don't worry too much, I was attempting a NEWKBD build under Linux. Without it, it builds fine.

I did fix some other compilation issues for NEWKBD, look at the latest commits on branch jgh-fixup on my repo.

-- Michael

On January 20, 2019 9:31:56 AM GMT, jgharston <notifications@github.com> wrote:
>Michael McConnell wrote:
>> HOWEVER - it won't build correctly on Unix, as in function kbd_get()
>> you're using a function getch() that doesn't exist as a function in
>> the Brandy code, nor is it a library function in Unix.
>
>Ah, I thought I'd carefully #ifdef'd around everything so only the
>MinGW 
>and
>DJGPP builds use the new code, as I hadn't started looking at the code 
>the
>other builds were using. I'll have a look later.
>
>-- 
>J.G.Harston - jgh@mdfs.net - mdfs.net/jgh
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/stardot/MatrixBrandy/pull/37#issuecomment-455850775

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by soruk42** [comment]
I've merged in your latest keyboard.c. The other changes look like your branch catching up with my changes.

**Comment by jgharston** [comment]
On 28-01-2019 10:03, Michael McConnell wrote:
> I've merged in your latest keyboard.c. The other changes look like
> your branch catching up with my changes.

Great, I'll re-syncrhonise back to the the master branch.

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Pull request closed without merging**
