### PR TITLE
Removing old keyboard code

### PR DESCRIPTION
**Pull request by jgharston**
This should build with identical functionality, commented out all old keyboard code in preparation to removing it. (Plus minor tidying in mos.c)
Haven't tested a Linux build, as I've forgotten how to boot my PC into Linux. :(

### CODE REVIEW

**Comment by soruk42** [comment]
Do you still have the CentOS7 VM in Virtualbox you downloaded from me a while back?

**Comment by soruk42** [comment]
FYI, it builds in (CentOS 6) Linux just fine with both NEWKBD and OLDKBD.

**Comment by jgharston** [comment]
On 27-08-2019 08:48, Michael McConnell wrote:
> Do you still have the CentOS7 VM in Virtualbox you downloaded from me
> a while back?

Yes, I suddenly remembered how to start it up. Double-click on the
.ova file. I'd been going through my Start Menu trying to track
down something to start it.

The Linux Build just needs sdlsound.c/.o adding to the makefile.

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by soruk42** [comment]
It's already there, resync with master.

Also, double-clicking on the ova file will import a fresh second copy. Start Oracle VM Virtualbox from your Start menu, and from that control panel start the VM.

On August 27, 2019 7:09:54 PM GMT+01:00, jgharston <notifications@github.com> wrote:
>On 27-08-2019 08:48, Michael McConnell wrote:
>> Do you still have the CentOS7 VM in Virtualbox you downloaded from me
>> a while back?
>
>Yes, I suddenly remembered how to start it up. Double-click on the
>.ova file. I'd been going through my Start Menu trying to track
>down something to start it.
>
>The Linux Build just needs sdlsound.c/.o adding to the makefile.
>
>-- 
>J.G.Harston - jgh@mdfs.net - mdfs.net/jgh
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/stardot/MatrixBrandy/pull/52#issuecomment-525419199

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
