### PR TITLE
Update to INKEY functions

### PR DESCRIPTION
**Pull request by jgharston**
I've been dragging a stiff comb through keyboard.c integrating all the
scattered code.

If NEWKBD is not defined it builds with the old keyboard handling code
and is functionally unchanged (and should be binary identical).

If NEWKBD is defined it builds with the new keyboard handling code.

All the platform-specific functions duplicate code which makes them more
appropriate to be single functions with bits of platform-specific code.
It also is gradually eliminating the BODGE identifiers I've had to put in
to get some of the builds working.

The majority of the INKEY code is now integrated and just depends on a
few bits of legacy code. Some of the legacy INKEY routines didn't even
support INKEY-256, so the first result was that all platforms support
INKEY-256 automatically.

+ve INKEY tested and works on: RISCOS:ok, WinSDL:ok, MGW:ok, DJP:ok
-ve INKEY tested and works on: RISCOS:ok, WinSDL:ok, MGW:ok, DJP:to do

The SDL builds now support testing for keys not known about by SDL by
using helper code for a handful of keyscan values.

DOS/Win builds without SDL now support negative INKEYs using code
from the JGH 'console' library.

### CODE REVIEW

**Comment by soruk42** [comment]
I'm not going to merge this to Master - the KBDNEW doesn't build on Linux.  The function int GetAsyncState(int x) is only defined for TARGET_DJGPP, but is being used by int32 kbd_inkey(int32 arg) even when TARGET_DJGPP is not declared.

**Comment by soruk42** [comment]
Patches I think you need to apply:
```
diff --git a/src/keyboard.c b/src/keyboard.c
index c7e4a29..0ffd6be 100644
--- a/src/keyboard.c
+++ b/src/keyboard.c
@@ -383,7 +383,7 @@ int GetAsyncKeyState(int x) {
 
 /* kbd_get called to implement Basic GET and GET$ functions */
 /* -------------------------------------------------------- */
-int32 kbd_get() {
+int32 kbd_get(void) {
 
 #ifdef TARGET_RISCOS
   // RISC OS, pass directly to MOS

```
... and ...
```
diff --git a/src/keyboard.h b/src/keyboard.h
index 3083c7b..9b57af2 100644
--- a/src/keyboard.h
+++ b/src/keyboard.h
@@ -43,6 +43,7 @@ extern void set_escint(int i);
 extern void set_escmul(int i);
 extern void osbyte44(int x);
 #ifdef NEWKBD
+extern int32 kbd_get(void);
 extern int32 kbd_inkey(int32);
 #endif
 #endif

```

**Comment by jgharston** [comment]
Michael McConnell wrote:
> I'm not going to merge this to Master - the KBDNEW doesn't build on
> Linux. The function int GetAsyncState(int x) is only defined for
> TARGET_DJGPP, but is being used by int32 kbd_inkey(int32 arg) even
> when TARGET_DJGPP is not declared.

Yes, I realised as I was drifting off to sleep after about six hours of
key-by-key, line-by-line testing. It needs:

       switch (arg) {  /* Not visible from SDL keyscan */
ifdef TARGET_DOSWIN
         case 32:  return (GetAsyncKeyState(0x2C)<0 ? -1 : 0); /* 
F0/PRINT */
...etc....
               GetAsyncKeyState(0xDC) == 0 ? -1 : 0); /* K#  #~ */
#endif
                   /* Translate SDL keyscan */

I can't do Git from this computer, I'll do an update tomorrow. I need to
get a working Unix build environment to catch these slips.

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by jgharston** [comment]
Michael McConnell wrote:
> -int32 kbd_get() {
> +int32 kbd_get(void) {
...

he he. I should really turn 'warnings' back on. ;)

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by soruk42** [comment]
>  I can't do Git from this computer, I'll do an update tomorrow. I need to get a working Unix build environment to catch these slips.

If you apply the fix I gave you in the *. thread for the VirtualBox shared folders then you should be able to use the VM you downloaded from me. Before I packaged it up, I ran a git clone from my internal git server and built Brandy for SDL and text mode, without error. (I then removed it, as it was pointing to my private server, you'd probably want it to point it to your branch.)

**Comment by soruk42** [comment]
There we go, merged.

**Pull request merged**
