### PR TITLE
Escape processing all moved to keyboard handler

### PR DESCRIPTION
**Pull request by jgharston**
Moved all checks for Escape processing into keyboard driver. Character input checks FX220, background check still polls physical key. Escape checks processed through FX229 and FX200.
Issues: Escape on WinSDL gives EscapeEscape.
This may need a manual merge for the files other than keyboard, as this is out of sync with the 64-bit fixes and he changes from longjmp to siglongjump. It should be mostly a single line in a couple of functions in each file calling kbd_escpoll().

### CODE REVIEW

**Comment by soruk42** [comment]
Manually merged to preserve the 64-bit and siglongjmp stuff.

**Comment by soruk42** [comment]
Another issue on the Windows build - it sometimes eats keypresses.

**Comment by jgharston** [comment]
On 27-09-2019 12:18, Michael McConnell wrote:
> Another issue on the Windows build - it sometimes eats keypresses.

Which Windows build? Win/SDL? I think this is related to the repeated
Escape I'm seeing, and think I've tracked where it's coming from.

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by soruk42** [comment]
Yes, I can't (yet) get non-SDL build working from MinGW (Cygwin build environment).

On September 27, 2019 1:33:22 PM GMT+01:00, jgharston <notifications@github.com> wrote:
>On 27-09-2019 12:18, Michael McConnell wrote:
>> Another issue on the Windows build - it sometimes eats keypresses.
>
>Which Windows build? Win/SDL? I think this is related to the repeated
>Escape I'm seeing, and think I've tracked where it's coming from.
>
>-- 
>J.G.Harston - jgh@mdfs.net - mdfs.net/jgh
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/stardot/MatrixBrandy/pull/66#issuecomment-535919779

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jgharston** [comment]
On 27-09-2019 13:34, Michael McConnell wrote:
> Yes, I can't (yet) get non-SDL build working from MinGW (Cygwin build
> environment).

Odd, it's been building here, on WinXP and Win7. My development
directory, including binaries freshly built just now, is:

http://mdfs.net/Software/BBCBasic/Brandy/Matrix20190928.zip

Is that using tools on Linux to build the MinGW build, or using tools
on Windows to build the MinGW build?

-- 
J.G.Harston - jgh@mdfs.net - mdfs.net/jgh

**Comment by soruk42** [comment]
Tools under Windows, using Cygwin as the development and build environment.

On September 28, 2019 8:43:28 PM GMT+01:00, jgharston <notifications@github.com> wrote:
>On 27-09-2019 13:34, Michael McConnell wrote:
>> Yes, I can't (yet) get non-SDL build working from MinGW (Cygwin build
>> environment).
>
>Odd, it's been building here, on WinXP and Win7. My development
>directory, including binaries freshly built just now, is:
>
>http://mdfs.net/Software/BBCBasic/Brandy/Matrix20190928.zip
>
>Is that using tools on Linux to build the MinGW build, or using tools
>on Windows to build the MinGW build?
>
>-- 
>J.G.Harston - jgh@mdfs.net - mdfs.net/jgh
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/stardot/MatrixBrandy/pull/66#issuecomment-536220013

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
